MockHTML = "<h2>Template Output</h2>\n\n{{#each this}}\n<div class='nm'>{{name}}</div>\n{{/each}}";

MockCSS = "body{background-color:#ff9900;}\n\nh2{\n  font-family:Arial;\n  text-decoration:underline;\n}\n\n.nm{\n  background-color:#ff4600;\n  width:100%;\n  margin:4px;\n  padding:2px;\n  text-align:center;\n  border-radius:8px;\n  color:white;\n}";


MockPeople = [
{"country":"Japan","date":"1/4/2015","city":"Ōmuta","company":"Trunyx","name":"Billy"},
{"country":"Cambodia","date":"10/3/2014","city":"Koh Kong","company":"Topdrive","name":"Nancy"},
{"country":"China","date":"8/3/2014","city":"Dabu","company":"Gabspot","name":"Jeremy"},
{"country":"China","date":"3/20/2014","city":"Zhuozishan","company":"Yamia","name":"Doris"},
{"country":"Russia","date":"3/10/2015","city":"Pavlovskaya","company":"Yoveo","name":"Joe"},
{"country":"Indonesia","date":"3/2/2015","city":"Rote","company":"Dynabox","name":"Joshua"},
{"country":"Philippines","date":"3/6/2014","city":"Lipa City","company":"Skilith","name":"Johnny"},
{"country":"Portugal","date":"9/16/2014","city":"Vista Alegre","company":"Devpoint","name":"Ann"},
{"country":"Czech Republic","date":"10/26/2014","city":"Loučeň","company":"Yotz","name":"Maria"},
{"country":"Philippines","date":"10/2/2014","city":"Pasacao","company":"Fanoodle","name":"Russell"},
{"country":"China","date":"2/10/2015","city":"Huangsha","company":"Voonte","name":"Sharon"},
{"country":"China","date":"7/20/2014","city":"Saparbay","company":"Brainlounge","name":"Patricia"},
{"country":"China","date":"6/28/2014","city":"Lianhe","company":"Tazz","name":"Jennifer"},
{"country":"South Africa","date":"11/26/2014","city":"Volksrust","company":"Vimbo","name":"Larry"},
{"country":"Portugal","date":"3/26/2014","city":"Vilarinho","company":"Meetz","name":"Kathryn"},
{"country":"Indonesia","date":"7/3/2014","city":"Nanganumba","company":"Skyble","name":"Susan"},
{"country":"North Korea","date":"10/19/2014","city":"Anbyŏn-ŭp","company":"Zoomzone","name":"Jason"},
{"country":"Morocco","date":"3/19/2014","city":"Tazarine","company":"Quire","name":"Joe"},
{"country":"Brazil","date":"9/5/2014","city":"Esteio","company":"Fivebridge","name":"Earl"},
{"country":"France","date":"2/28/2015","city":"Cran-Gevrier","company":"Mydeo","name":"Chris"},
{"country":"China","date":"11/17/2014","city":"Jinji","company":"Jabbersphere","name":"Kimberly"},
{"country":"Sweden","date":"3/8/2014","city":"Danderyd","company":"Jetpulse","name":"Eric"},
{"country":"South Africa","date":"1/8/2015","city":"Burgersdorp","company":"Edgewire","name":"Lori"},
{"country":"Guinea","date":"12/16/2014","city":"Koubia","company":"Shufflebeat","name":"Phyllis"},
{"country":"China","date":"9/11/2014","city":"Bijia","company":"Skajo","name":"Kathy"},
{"country":"Portugal","date":"3/18/2014","city":"Amadora","company":"Skidoo","name":"Eric"},
{"country":"Indonesia","date":"3/12/2015","city":"Karangsari","company":"Feedmix","name":"Dorothy"},
{"country":"Israel","date":"6/29/2014","city":"Bu‘eina","company":"Kwideo","name":"Ralph"},
{"country":"Indonesia","date":"10/29/2014","city":"Pulorejo","company":"Oyondu","name":"Virginia"},
{"country":"United Arab Emirates","date":"3/10/2014","city":"Ras al-Khaimah","company":"Devcast","name":"Gary"},
{"country":"Malaysia","date":"10/29/2014","city":"Kuala Lumpur","company":"Zooxo","name":"Terry"},
{"country":"Finland","date":"10/14/2014","city":"Kaavi","company":"Trupe","name":"Joan"},
{"country":"China","date":"5/10/2014","city":"Xiangdian","company":"Demivee","name":"Harold"},
{"country":"Ireland","date":"5/17/2014","city":"Kill","company":"Divape","name":"Mildred"},
{"country":"Indonesia","date":"4/17/2014","city":"Pangatikan","company":"Mycat","name":"Lillian"},
{"country":"Indonesia","date":"2/1/2015","city":"Poteran","company":"Quatz","name":"Nicole"},
{"country":"Russia","date":"10/18/2014","city":"Nyurba","company":"Einti","name":"Pamela"},
{"country":"China","date":"4/3/2014","city":"Ning’er","company":"Voonyx","name":"Jane"},
{"country":"Indonesia","date":"8/12/2014","city":"Jenang Selatan","company":"Tazzy","name":"Frances"}]